### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by Martin-Pitt** [sdras/JS-stroll#4]
Thoughts on moving the branch to gh-pages so that it's always available served from github?

**Comment by sdras** [comment]
Right now I'm happy having the examples on codepen only, but maybe when I'm further in I'll set something like that up. The advantage to hosting the pens on codepen is that people can fork, see the output easily, and reverse engineer the work there. 

They're all in a collection there but unfortunately you can't see them inside the collection because it's private. I might ask if the visibility can be changed, though, as that would be more helpful.
